# Generated by Django 3.0.5 on 2020-04-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='no_of_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.TextField(default='', max_length=600),
            preserve_default=False,
        ),
    ]
