# Generated by Django 3.0.5 on 2020-04-29 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200429_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('post', models.TextField(max_length=600)),
                ('no_of_posts', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('stuffs_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
