# Generated by Django 3.0.5 on 2020-04-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200429_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuffs',
            name='stuffs_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuffs', to='blog_app.User'),
        ),
    ]
