# Generated by Django 3.0.5 on 2020-04-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200429_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuffs',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='stuffs',
            name='no_of_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
