# Generated by Django 3.0.5 on 2020-04-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20200429_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=2000)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('post_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog_app.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Stuffs',
        ),
    ]
