# Generated by Django 3.0.5 on 2020-05-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_auto_20200507_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'likes'},
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog_app.User'),
        ),
    ]
