# Generated by Django 3.0.5 on 2020-05-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20200512_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog_app.User'),
        ),
    ]
