# Generated by Django 3.0.5 on 2020-05-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20200512_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='C:\\Users\\Godwin\\Desktop\\Godwyn\\pix1072366_XL.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
