# Generated by Django 3.0.5 on 2020-05-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='C:/Users/Godwin/Desktop/Godwyn/pix/1072366_XL.jpg', upload_to=''),
        ),
    ]
