# Generated by Django 3.0.5 on 2020-05-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_auto_20200523_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
