# Generated by Django 3.0.5 on 2020-05-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0018_auto_20200524_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('likes_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_value', to='blog_app.Posts')),
            ],
        ),
    ]
