# Generated by Django 3.0.5 on 2020-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_auto_20200526_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='C:\\Users\\Godwin\\django\\Blog\\blog_app\\static\\img\\camera-1809-461609.png', upload_to=''),
        ),
    ]
