# Generated by Django 3.0.5 on 2020-05-28 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_auto_20200527_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=None)),
                ('comments', models.TextField(max_length=5000)),
                ('comments_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to='blog_app.Posts')),
            ],
        ),
    ]
