# Generated by Django 3.0.5 on 2020-05-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_id',
        ),
    ]
