# Generated by Django 3.0.5 on 2020-05-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0025_remove_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
