# Generated by Django 3.0.5 on 2020-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0028_auto_20200528_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.CharField(max_length=400),
        ),
    ]
