# Generated by Django 3.0.5 on 2020-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0029_auto_20200529_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
